model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  freeze_ecg: true
  freeze_phi: true
  freeze_qformer: true
  lora_r: 64
  lora_alpha: 16
  ecg_model: ecg_vit
  seq_len: 1000
  patch_size:
  - 1
  - 200
  ckpt: /home/cmpdil/Iit_profbehra/TinyGPT-ECG/TinyGPT-V-main/minigpt4/output/ecg_gpt_stage2/20260429210/checkpoint_1.pth
datasets:
  ecg_dataset:
    batch_size: 8
    ecg_processor:
      train:
        name: base_processor
    text_processor:
      train:
        name: blip_caption
    build_info:
      vis_root: 
      ann_paths: /home/cmpdil/Iit_profbehra/TinyGPT-ECG/TinyGPT-V-main/data/stage3.json
run:
  task: ecg_text_pretrain
  lr_sched: linear_warmup_cosine_lr
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6
  weight_decay: 0.05
  max_epoch: 1
  num_workers: 4
  warmup_steps: 5000
  iters_per_epoch: 140000
  seed: 42
  output_dir: output/ecg_gpt_stage3
  amp: true
  resume_ckpt_path: null
  evaluate: false
  train_splits:
  - train
  device: cuda
  world_size: 1
  dist_url: env://
  distributed: true
  wandb_log: true
  job_name: ecg_gpt_stage3
