model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  ckpt: ''
  use_grad_checkpoint: true
  lora_r: 64
  lora_alpha: 16
  ecg_model: ecg_vit
  seq_len: 1000
  patch_size:
  - 1
  - 200
datasets:
  laion:
    batch_size: 64
    ecg_processor:
      train:
        name: base_processor
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 115
  cc_sbu:
    batch_size: 64
    ecg_processor:
      train:
        name: base_processor
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 14
run:
  task: ecg_text_pretrain
  lr_sched: linear_warmup_cosine_lr
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6
  weight_decay: 0.05
  max_epoch: 4
  num_workers: 4
  warmup_steps: 5000
  iters_per_epoch: 5000
  seed: 42
  output_dir: output/minigpt4_stage1_pretrain
  amp: true
  resume_ckpt_path: null
  evaluate: false
  train_splits:
  - train
  device: cuda
  world_size: 1
  dist_url: env://
  distributed: true
  wandb_log: true
  job_name: minigpt4_pretrain
