model:
  arch: minigpt4

  # ecg encoder
  ecg_model: "ecg_vit"
  seq_len: 1000
  patch_size: [1, 200]
  pretrained_ecg: "/home/cmpdil/iit_profbehra2/pretrained/vit_base_sigmoid/model_epoch9 copy.bin"
  freeze_ecg: True
  use_grad_checkpoint: False


  # generation configs
  prompt: ""

  llama_model: "Qwen/Qwen3.5-9B"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]

preprocess:
    ecg_processor:
        train:
          name: "base_processor"
        eval:
          name: "base_processor"
    text_processor:
        train:
          name: "base_processor"
        eval:
          name: "base_processor"
